### ISSUE TITLE
Windows: tests fail with --incompatible_windows_native_test_wrapper 

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel-integration-testing#148]
Windows 10
Bazel 0.28.1

```
PATH=c:\git\mingw64\bin;c:\src\bazel-releases\current;c:\windows\system32
```

Tests pass with `--noincompatible_windows_native_test_wrapper`:

```
C:\src\tw-migrations\bazel-integration-testing>bazel --ignore_all_rc_files --output_user_root=c:/b test --repository_cache=  --noincompatible_windows_native_test_wrapper --enable_runfiles //javatests/build/bazel/tests/integration:BazelBaseTestCaseTest/bazel0.21.0 --noincompatible_string_join_requires_strings --test_env=BAZEL_VC --test_env=JAVA_HOME
(...)
//javatests/build/bazel/tests/integration:BazelBaseTestCaseTest/bazel0.21.0 PASSED in 33.0s
```

Tests fail with `--incompatible_windows_native_test_wrapper`:
```
Executing tests from //javatests/build/bazel/tests/integration:BazelBaseTestCaseTest/bazel0.21.0
-----------------------------------------------------------------------------
JUnit4 Test Runner
E
Time: 0.032
There was 1 failure:
1) build.bazel.tests.integration.BazelBaseTestCaseTest
java.io.FileNotFoundException: javatests\build\bazel\tests\integration\BazelBaseTestCaseTest\config0.21.0.properties (The system cannot find the path specified)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at java.io.FileInputStream.<init>(FileInputStream.java:93)
        at build.bazel.tests.integration.WorkspaceDriver.loadProperties(WorkspaceDriver.java:104)
        at build.bazel.tests.integration.WorkspaceDriver.setUpClass(WorkspaceDriver.java:58)
        at build.bazel.tests.integration.BazelBaseTestCase.setUpClass(BazelBaseTestCase.java:28)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
        at com.google.testing.junit.runner.internal.junit4.CancellableRequestFactory$CancellableRunner.run(CancellableRequestFactory.java:89)
        at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
        at org.junit.runner.JUnitCore.run(JUnitCore.java:138)
        at com.google.testing.junit.runner.junit4.JUnit4Runner.run(JUnit4Runner.java:112)
        at com.google.testing.junit.runner.BazelTestRunner.runTestsInSuite(BazelTestRunner.java:153)
        at com.google.testing.junit.runner.BazelTestRunner.main(BazelTestRunner.java:84)

FAILURES!!!
Tests run: 0,  Failures: 1
```

Contents of `bazel-bin\javatests\build\bazel\tests\integration\BazelBaseTestCaseTest\config0.21.0.properties`:
```
C:\src\tw-migrations\bazel-integration-testing>type bazel-bin\javatests\build\bazel\tests\integration\BazelBaseTestCaseTest\config0.21.0.properties
bazel.version=0.21.0
bazel.workspace=build_bazel_integration_testing
bazel.external.deps=
java_home_runfiles_path=../local_jdk
```

This is blocking https://github.com/bazelbuild/bazel/issues/6622.

**Comment by laszlocsomor** [comment]
Complete list of failed tests with this flag:

"Artifacts" tab on https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1109#14a52d5d-cd56-4949-a949-515bb7db025a

**Comment by laszlocsomor** [comment]
Looks like it's actually a test wrapper bug, same as https://github.com/bazelbuild/bazel/issues/9009#issuecomment-516361166.

**Comment by laszlocsomor** [comment]
Closing in favor of https://github.com/bazelbuild/bazel/issues/9009
